/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projeklibrary;

import java.util.ArrayList;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.Persistence;
import javax.persistence.Query;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import static org.eclipse.persistence.internal.jpa.metadata.xml.XMLEntityMappingsReader.clear;

/**
 *
 * @author LUI
 */
public class Anggota extends javax.swing.JPanel {

    /**
     * Creates new form Anggota
     */
    //private Anggota tbl = new Anggota();
    private List<Peminjam> listAnggota = new ArrayList<>();
    
    List<Peminjam> mod = null;

    public Anggota() {
        initComponents();
        loadData();
    }

//    Anggota(Object object, boolean b) {
//        
//        initComponents();
//        tbl_ang.setModel((TableModel) tbl);
//        List<Peminjaman> list = servisPeminjaman.ambilData();
//        jLabel1.requestFocus();
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_ang = new javax.swing.JTable();
        tf_cari = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        cbx_cari = new javax.swing.JComboBox<>();
        jButtonTambah = new javax.swing.JButton();
        jButtonHapus = new javax.swing.JButton();
        jButtonUbah = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        tbl_ang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Anggota", "Nama", "NIM", "Program Studi", "Fakultas", "Alamat", "Telephone", "E-mail", "Semester"
            }
        ));
        jScrollPane1.setViewportView(tbl_ang);

        tf_cari.setText("Cari");
        tf_cari.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tf_cariFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf_cariFocusLost(evt);
            }
        });
        tf_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_cariActionPerformed(evt);
            }
        });
        tf_cari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf_cariKeyTyped(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Search.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        cbx_cari.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID Anggota", "Nama", "NIM", "Fakultas", "Prodi", "Alamat", " " }));
        cbx_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_cariActionPerformed(evt);
            }
        });

        jButtonTambah.setBackground(new java.awt.Color(102, 0, 0));
        jButtonTambah.setForeground(new java.awt.Color(255, 255, 255));
        jButtonTambah.setText("TAMBAH");
        jButtonTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTambahActionPerformed(evt);
            }
        });

        jButtonHapus.setBackground(new java.awt.Color(102, 0, 0));
        jButtonHapus.setForeground(new java.awt.Color(255, 255, 255));
        jButtonHapus.setText("HAPUS");
        jButtonHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHapusActionPerformed(evt);
            }
        });

        jButtonUbah.setBackground(new java.awt.Color(102, 0, 0));
        jButtonUbah.setForeground(new java.awt.Color(255, 255, 255));
        jButtonUbah.setText("UBAH");
        jButtonUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUbahActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/petugas.png"))); // NOI18N
        jLabel1.setText("DAFTAR ANGGOTA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 817, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonTambah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonHapus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tf_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cbx_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tf_cari)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addComponent(cbx_cari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonTambah)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonHapus)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonUbah))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tf_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_cariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_cariActionPerformed

    private void cbx_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_cariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_cariActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String sc = tf_cari.getText();
        if (sc.equals("Cari")) {
            loadData();
        } else {

            switch (cbx_cari.getSelectedIndex()) {
                case 0:
                    getByID(sc);
                    break;
                case 1:
                    getByNama(sc);
                    break;
                case 2:
                    getByNim(sc);
                    break;
                case 3:
                    getByFakultas(sc);
                    break;
                case 4:
                    getByProdi(sc);
                    break;
                case 5:
                    getByAlamat(sc);
                    break;

            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTambahActionPerformed
        new InputAnggota(null, true).setVisible(true);
        loadData();
    }//GEN-LAST:event_jButtonTambahActionPerformed

    private void jButtonHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHapusActionPerformed
        EntityManager em = Persistence.createEntityManagerFactory("ProjekLibraryPU").createEntityManager();
        em.getTransaction().begin();
        Peminjam p = em.find(Peminjam.class, tbl_ang.getValueAt(tbl_ang.getSelectedRow(), 0).toString());
        em.remove(p);
        em.getTransaction().commit();
        em.close();
    }//GEN-LAST:event_jButtonHapusActionPerformed

    private void jButtonUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUbahActionPerformed

        if (tbl_ang.getSelectedRow() < 0) {
            JOptionPane.showMessageDialog(this, "Pilih Data Terlebih Dahulu");
        } else {
            String s = (String) tbl_ang.getValueAt(tbl_ang.getSelectedRow(), 0);
            new InputAnggota(null, true, s).setVisible(true);
        }
        loadData();
    }//GEN-LAST:event_jButtonUbahActionPerformed

    private void tf_cariFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_cariFocusGained
        String s = tf_cari.getText();
        if (s.equals("")) {
            tf_cari.setText("Cari");
        }
    }//GEN-LAST:event_tf_cariFocusGained

    private void tf_cariFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_cariFocusLost
        String s = tf_cari.getText();
        if (s.equals("")) {
            tf_cari.setText("Cari");
        }
    }//GEN-LAST:event_tf_cariFocusLost

    private void tf_cariKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_cariKeyTyped
       char c = evt.getKeyChar();
        if (c == '\n') {
            jButton1ActionPerformed(null);
        }
    }//GEN-LAST:event_tf_cariKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbx_cari;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonHapus;
    private javax.swing.JButton jButtonTambah;
    private javax.swing.JButton jButtonUbah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_ang;
    private javax.swing.JTextField tf_cari;
    // End of variables declaration//GEN-END:variables

    private void loadData() {
        EntityManager em = Persistence.createEntityManagerFactory("ProjekLibraryPU").createEntityManager();
        em.getTransaction().begin();
        Query query = em.createQuery("SELECT p FROM Peminjam p ORDER BY p.idPeminjam");
        List<Peminjam> list = query.getResultList();
        em.getTransaction().commit();
        em.close();
        DefaultTableModel tbl1 = (DefaultTableModel) tbl_ang.getModel();
        tbl1.setRowCount(0);
        tbl_ang.setModel(tbl1);
        mod = list;
        for (Peminjam p : list) {
            tbl1.addRow(new Object[]{
                p.getIdPeminjam(),
                p.getNama(),
                p.getNim(),
                p.getProgramStudi(),
                p.getFakultas(),
                p.getAlamat(),
                p.getTelephone(),
                p.getEmail(),
                p.getSemester()

            });
        }

    }

    public List<Peminjam> getByID(String id) {
        EntityManager em = Persistence.createEntityManagerFactory("LibraLinxPU").createEntityManager();
        em.getTransaction().begin();
        Query query = em.createQuery("SELECT p FROM Peminjam p WHERE LOWER(p.idPeminjam) LIKE :idPeminjam ORDER BY p.idPeminjam");
        query.setParameter("idPeminjam", "%" + id.toLowerCase() + "%");
        List<Peminjam> list = query.getResultList();
        em.getTransaction().commit();
        em.close();
        return list;
    }

    public List<Peminjam> getByNama(String nama) {
        EntityManager em = Persistence.createEntityManagerFactory("LibraLinxPU").createEntityManager();
        em.getTransaction().begin();
        Query query = em.createQuery("SELECT p FROM Peminjam p WHERE LOWER(p.nama) LIKE :nama ORDER BY p.idPeminjam");
        query.setParameter("nama", "%" + nama.toLowerCase() + "%");
        List<Peminjam> list = query.getResultList();
        em.getTransaction().commit();
        em.close();
        return list;
    }

    public List<Peminjam> getByNim(String nim) {
        EntityManager em = Persistence.createEntityManagerFactory("LibraLinxPU").createEntityManager();
        em.getTransaction().begin();
        Query query = em.createQuery("SELECT p FROM Peminjam p WHERE LOWER(p.nim) LIKE :nim ORDER BY p.idPeminjam");
        query.setParameter("nim", "%" + nim.toLowerCase() + "%");
        List<Peminjam> list = query.getResultList();
        em.getTransaction().commit();
        em.close();
        return list;
    }

    public List<Peminjam> getByFakultas(String fakultas) {
        EntityManager em = Persistence.createEntityManagerFactory("LibraLinxPU").createEntityManager();
        em.getTransaction().begin();
        Query query = em.createQuery("SELECT p FROM Peminjam p WHERE LOWER(p.fakultas) LIKE :fakultas ORDER BY p.idPeminjam");
        query.setParameter("fakultas", "%" + fakultas.toLowerCase() + "%");
        List<Peminjam> list = query.getResultList();
        em.getTransaction().commit();
        em.close();
        return list;
    }

    public List<Peminjam> getByProdi(String prodi) {
        EntityManager em = Persistence.createEntityManagerFactory("LibraLinxPU").createEntityManager();
        em.getTransaction().begin();
        Query query = em.createQuery("SELECT p FROM Peminjam p WHERE LOWER(p.programStudi) LIKE :prodi ORDER BY p.idPeminjam");
        query.setParameter("prodi", "%" + prodi.toLowerCase() + "%");
        List<Peminjam> list = query.getResultList();
        em.getTransaction().commit();
        em.close();
        return list;
    }

    public List<Peminjam> getByAlamat(String alamat) {
        EntityManager em = Persistence.createEntityManagerFactory("LibraLinxPU").createEntityManager();
        em.getTransaction().begin();
        Query query = em.createQuery("SELECT p FROM Peminjam p WHERE LOWER(p.alamat) LIKE :alamat ORDER BY p.idPeminjam");
        query.setParameter("alamat", "%" + alamat.toLowerCase() + "%");
        List<Peminjam> list = query.getResultList();
        em.getTransaction().commit();
        em.close();
        return list;
    }


}
